<?php

namespace Database\Seeders;

use App\Models\Personnel;
use Illuminate\Database\Seeder;

class PersonnelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $personnels = [
            [
                'matricule' => 'EMP001',
                'nom' => 'Dubois',
                'prenom' => 'Jean',
                'email' => 'jean.dubois@montaza.fr',
                'telephone' => '0123456789',
                'telephone_mobile' => '0612345678',
                'poste' => 'Directeur Général',
                'departement' => 'Direction',
                'date_embauche' => '2015-01-15',
                'salaire' => 5500.00,
                'adresse' => '15 Rue de la République',
                'ville' => 'Paris',
                'code_postal' => '75001',
                'numero_securite_sociale' => '1 85 02 75 001 123 45',
                'statut' => 'actif',
                'notes' => 'Fondateur de l\'entreprise',
            ],
            [
                'matricule' => 'EMP002',
                'nom' => 'Martin',
                'prenom' => 'Sophie',
                'email' => 'sophie.martin@montaza.fr',
                'telephone' => '0123456790',
                'telephone_mobile' => '0612345679',
                'poste' => 'Responsable Ressources Humaines',
                'departement' => 'Ressources Humaines',
                'date_embauche' => '2016-03-20',
                'salaire' => 3800.00,
                'adresse' => '28 Avenue des Champs',
                'ville' => 'Lyon',
                'code_postal' => '69001',
                'numero_securite_sociale' => '2 88 05 69 001 234 56',
                'statut' => 'actif',
                'notes' => null,
            ],
            [
                'matricule' => 'EMP003',
                'nom' => 'Bernard',
                'prenom' => 'Pierre',
                'email' => 'pierre.bernard@montaza.fr',
                'telephone' => '0123456791',
                'telephone_mobile' => '0612345680',
                'poste' => 'Chef de Projet',
                'departement' => 'Production',
                'date_embauche' => '2017-06-10',
                'salaire' => 4200.00,
                'adresse' => '42 Rue Victor Hugo',
                'ville' => 'Marseille',
                'code_postal' => '13001',
                'numero_securite_sociale' => '1 90 08 13 001 345 67',
                'statut' => 'actif',
                'notes' => 'Coordinateur des projets industriels',
            ],
            [
                'matricule' => 'EMP004',
                'nom' => 'Petit',
                'prenom' => 'Marie',
                'email' => 'marie.petit@montaza.fr',
                'telephone' => '0123456792',
                'telephone_mobile' => '0612345681',
                'poste' => 'Comptable',
                'departement' => 'Comptabilité',
                'date_embauche' => '2018-02-14',
                'salaire' => 3200.00,
                'adresse' => '7 Impasse des Lilas',
                'ville' => 'Toulouse',
                'code_postal' => '31000',
                'numero_securite_sociale' => '2 92 11 31 001 456 78',
                'statut' => 'actif',
                'notes' => null,
            ],
            [
                'matricule' => 'EMP005',
                'nom' => 'Rousseau',
                'prenom' => 'Thomas',
                'email' => 'thomas.rousseau@montaza.fr',
                'telephone' => '0123456793',
                'telephone_mobile' => '0612345682',
                'poste' => 'Technicien',
                'departement' => 'Maintenance',
                'date_embauche' => '2019-05-22',
                'salaire' => 2800.00,
                'adresse' => '33 Boulevard Gambetta',
                'ville' => 'Bordeaux',
                'code_postal' => '33000',
                'numero_securite_sociale' => '1 94 03 33 001 567 89',
                'statut' => 'actif',
                'notes' => 'Spécialiste en maintenance préventive',
            ],
            [
                'matricule' => 'EMP006',
                'nom' => 'Laurent',
                'prenom' => 'Julie',
                'email' => 'julie.laurent@montaza.fr',
                'telephone' => '0123456794',
                'telephone_mobile' => '0612345683',
                'poste' => 'Assistante Administrative',
                'departement' => 'Administration',
                'date_embauche' => '2019-09-01',
                'salaire' => 2500.00,
                'adresse' => '12 Rue Jean Jaurès',
                'ville' => 'Nantes',
                'code_postal' => '44000',
                'numero_securite_sociale' => '2 95 07 44 001 678 90',
                'statut' => 'actif',
                'notes' => null,
            ],
            [
                'matricule' => 'EMP007',
                'nom' => 'Moreau',
                'prenom' => 'David',
                'email' => 'david.moreau@montaza.fr',
                'telephone' => '0123456795',
                'telephone_mobile' => '0612345684',
                'poste' => 'Commercial',
                'departement' => 'Ventes',
                'date_embauche' => '2020-01-15',
                'salaire' => 3500.00,
                'adresse' => '56 Avenue de la Liberté',
                'ville' => 'Strasbourg',
                'code_postal' => '67000',
                'numero_securite_sociale' => '1 87 04 67 001 789 01',
                'statut' => 'actif',
                'notes' => 'Responsable secteur Est',
            ],
            [
                'matricule' => 'EMP008',
                'nom' => 'Simon',
                'prenom' => 'Émilie',
                'email' => 'emilie.simon@montaza.fr',
                'telephone' => '0123456796',
                'telephone_mobile' => '0612345685',
                'poste' => 'Ingénieur Qualité',
                'departement' => 'Qualité',
                'date_embauche' => '2020-08-01',
                'salaire' => 3900.00,
                'adresse' => '89 Rue de Rivoli',
                'ville' => 'Lille',
                'code_postal' => '59000',
                'numero_securite_sociale' => '2 89 12 59 001 890 12',
                'statut' => 'en_conge',
                'notes' => 'En congé maternité jusqu\'au 30/03/2026',
            ],
            [
                'matricule' => 'EMP009',
                'nom' => 'Lefevre',
                'prenom' => 'Nicolas',
                'email' => 'nicolas.lefevre@montaza.fr',
                'telephone' => '0123456797',
                'telephone_mobile' => '0612345686',
                'poste' => 'Magasinier',
                'departement' => 'Logistique',
                'date_embauche' => '2021-03-10',
                'salaire' => 2400.00,
                'adresse' => '21 Place de la Mairie',
                'ville' => 'Rennes',
                'code_postal' => '35000',
                'numero_securite_sociale' => '1 96 06 35 001 901 23',
                'statut' => 'actif',
                'notes' => 'Gestion des stocks et réceptions',
            ],
            [
                'matricule' => 'EMP010',
                'nom' => 'Roux',
                'prenom' => 'Céline',
                'email' => 'celine.roux@montaza.fr',
                'telephone' => '0123456798',
                'telephone_mobile' => '0612345687',
                'poste' => 'Secrétaire',
                'departement' => 'Administration',
                'date_embauche' => '2022-01-05',
                'date_depart' => '2025-12-31',
                'salaire' => 2300.00,
                'adresse' => '5 Cours Lafayette',
                'ville' => 'Grenoble',
                'code_postal' => '38000',
                'numero_securite_sociale' => '2 97 09 38 001 012 34',
                'statut' => 'parti',
                'notes' => 'Démission pour raisons personnelles',
            ],
        ];

        foreach ($personnels as $personnel) {
            Personnel::create($personnel);
        }
    }
}
